#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2001-11  Iñigo Serna
# Time-stamp: <2011-05-08 01:31:02 inigo>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys
from lfm.lfm import lfm_start

if sys.version_info < (2, 5):
    print "Python 2.5 or higher is required to run lfm."
else:
    lfm_start(sys.argv)
